<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>foodName_1</name>
   <tag></tag>
   <elementGuidId>369136ca-4f17-4347-ac65-938f968dbd8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sub-food > h4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div/h4[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>25b8169f-6498-4058-8c05-fea49c850e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>haejangguk</value>
      <webElementGuid>4435911e-9920-4c03-893f-e2d6af0fef92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;food&quot;]/div[@class=&quot;sub-food&quot;]/h4[1]</value>
      <webElementGuid>98c0df3d-42ab-47a6-ba04-0faa18b86ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Food'])[1]/following::h4[1]</value>
      <webElementGuid>34b41f51-7517-4f64-bbf0-7e233718339f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::h4[1]</value>
      <webElementGuid>086dbc50-3940-4055-824c-d704148ce0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='thick and spicy soup made from beef bone'])[1]/preceding::h4[1]</value>
      <webElementGuid>ab405c4a-977d-45c0-a335-a5beb6176da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kimbup'])[1]/preceding::h4[2]</value>
      <webElementGuid>768f7bda-7c50-4f0f-88de-e5bc3c6248f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='haejangguk']/parent::*</value>
      <webElementGuid>ca72c948-d4f4-4418-b241-9a0ddb262bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/h4</value>
      <webElementGuid>75d00524-f17e-4e1d-96b7-da0bac1962de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'haejangguk' or . = 'haejangguk')]</value>
      <webElementGuid>44f2ad57-a385-49b7-adbc-3e9382a57219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
