<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Order Now</name>
   <tag></tag>
   <elementGuidId>7919de82-bb45-421c-9b4d-681f23a3c498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.bottomhome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;document.location='login'&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e1e6c747-c346-4cf6-9bc5-d2067dbf9331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bottomhome</value>
      <webElementGuid>fd127430-cfb4-4319-99f5-3e94acd59d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.location='login'</value>
      <webElementGuid>f04e95d3-e4c9-4892-9ccc-99047a0785aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order Now</value>
      <webElementGuid>72438190-c94d-42ca-9b21-1b11bd935261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main&quot;]/div[@class=&quot;bottom&quot;]/button[@class=&quot;bottomhome&quot;]</value>
      <webElementGuid>64e9e96c-2649-437a-8d18-1d3ae91255ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;document.location='login'&quot;]</value>
      <webElementGuid>ee9c862a-8b70-4757-ab7e-725d8ffd87cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enjoy a good time with the best dishes in restaurant and improve your day'])[1]/following::button[1]</value>
      <webElementGuid>e6a6016b-9ff7-4c6d-8967-da4d952620bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enjoy Delicious Korean Food'])[1]/following::button[1]</value>
      <webElementGuid>3be828dd-d928-4ba9-b8af-b11c36c9e6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order Now']/parent::*</value>
      <webElementGuid>9ecdb8e8-280c-4c52-9ec7-ca43fdc204fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>19fe7b37-c826-435d-864e-8c264dbc21f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Order Now' or . = 'Order Now')]</value>
      <webElementGuid>3e438704-841b-4493-b15f-253fb549f276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
